### ISSUE TITLE
Vocab for Target Side i.e. Decoder

### ISSUE THREAD

**Issue by adarsh-kr** [jasonwu0731/trade-dst#1]
Can you please explain what is the rationale behind adding `"t{}".format(time_i)`as part of the vocab of target side?

Ref: https://github.com/jasonwu0731/trade-dst/blob/master/utils/utils_multiWOZ_DST.py#L324

**Comment by jasonwu0731** [comment]
Hi Adarsh,

That part is used for some other experimental settings, so the "mem_lang" is not used at all. Please feel free to remove that part. Thanks.
