### ISSUE TITLE
Issue with Equation 2 in paper

### ISSUE THREAD

**Issue by prafulla77** [jasonwu0731/trade-dst#11]
How did you get R^|V| vector with P_{jk}^history? From what I understood, (1-P_jk^gen )is a scalar and P_{jk}^history is a vector of size |X_t|. How does that add to P_{jk}^vocab?

**Comment by jasonwu0731** [comment]
You can check how I do this in the code. Basically, you need to use a built-in function called scatter_add_()

https://github.com/jasonwu0731/trade-dst/blob/master/models/TRADE.py#L455

**Comment by failable** [comment]
But I think the equation itself is still wrong in math due to the two vectors have different dimensions.
