### ISSUE TITLE
The target value vocabulary

### ISSUE THREAD

**Issue by Shuailong** [jasonwu0731/trade-dst#15]
It seems that the vocabulary of the slot values are not added to the vocabulary, E.g., `dontcare`. Only the system and user utterance tokens are added. How does the model generate the tokens which are not from the dialog history context?

**Comment by jasonwu0731** [comment]
The ideal way will be reserving a empty distribution for unknown words, similar to the implementation [here](https://github.com/salesforce/decaNLP/blob/master/models/pointer_generator.py).

We simplify the setting by adding all the vocabulary, and yes we should also add all the possible slot values (can possibly get a better result). For the "dontcare" value you pointed out, in our case we mainly generate that value using slot gate.

Hope this help.
