### ISSUE TITLE
BadZipFile Error when runing myTrain.py, using python3.7

### ISSUE THREAD

**Issue by kriszhao** [jasonwu0731/trade-dst#19]
$ python3 myTrain.py -dec=TRADE -bsz=32 -dr=0.2 -lr=0.001 -le=1

[Warning] Using hidden size = 400 for pretrained word embedding (300 + 100)...
{'dataset': 'multiwoz', 'task': 'dst', 'path': None, 'sample': None, 'patience': 6, 'earlyStop': 'BLEU', 'all_vocab': 1, 'imbalance_sampler': 0, 'data_ratio': 100, 'unk_mask': 1, 'batch': 32, 'run_dev_testing': 0, 'vizualization': 0, 'genSample': 0, 'evalp': 1, 'addName': '', 'eval_batch': 0, 'use_gate': 1, 'load_embedding': 1, 'fix_embedding': 0, 'parallel_decode': 0, 'decoder': 'TRADE', 'hidden': 400, 'learn': 0.001, 'drop': 0.2, 'limit': -10000, 'clip': 10, 'teacher_forcing_ratio': 0.5, 'lambda_ewc': 0.01, 'fisher_sample': 0, 'all_model': False, 'domain_as_task': False, 'run_except_4d': 1, 'strict_domain': False, 'except_domain': '', 'only_domain': ''}
folder_name save/TRADE-multiwozdst/
Reading from data/train_dials.json
domain_counter {'hotel': 3381, 'train': 3103, 'attraction': 2717, 'restaurant': 3813, 'taxi': 1654}
Reading from data/dev_dials.json
domain_counter {'hotel': 416, 'train': 484, 'attraction': 401, 'restaurant': 438, 'taxi': 207}
Reading from data/test_dials.json
domain_counter {'taxi': 195, 'attraction': 395, 'restaurant': 437, 'train': 494, 'hotel': 394}
[Info] Loading saved lang files...
Dumping pretrained embeddings...
Traceback (most recent call last):
  File "myTrain.py", line 22, in <module>
    train, dev, test, test_special, lang, SLOTS_LIST, gating_dict, max_word = prepare_data_seq(True, args['task'], False, batch_size=int(args['batch']))
  File "/home/**/trade-dst/utils/utils_multiWOZ_DST.py", line 426, in prepare_data_seq
    dump_pretrained_emb(lang.word2index, lang.index2word, emb_dump_path)
  File "/home/**/trade-dst/utils/utils_multiWOZ_DST.py", line 362, in dump_pretrained_emb
    embeddings = [GloveEmbedding(), KazumaCharEmbedding()]
  File "/home/**/miniconda3/lib/python3.7/site-packages/embeddings/glove.py", line 48, in __init__
    self.load_word2emb(show_progress=show_progress)
  File "/home/**/miniconda3/lib/python3.7/site-packages/embeddings/glove.py", line 65, in load_word2emb
    with zipfile.ZipFile(fin_name) as fin:
  File "/home/**/miniconda3/lib/python3.7/zipfile.py", line 1258, in __init__
    self._RealGetContents()
  File "/home/**/miniconda3/lib/python3.7/zipfile.py", line 1325, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by jasonwu0731** [comment]
Hi, 

Please double check if you have successfully downloaded the Glove package. The error message looks like the zip file is not well downloaded.

**Comment by kriszhao** [comment]
Thanks for the reply. I think I got the glove package.
$ pip3 freeze | grep glove
glove==1.0.1
