### ISSUE TITLE
Few short training error

### ISSUE THREAD

**Issue by ahtsham58** [jasonwu0731/trade-dst#21]
Hi @andreamad8 @jasonwu0731 ,

I am facing a path error, dont know if the command format is correct for "Few short DST"
here is the error log..

![image](https://user-images.githubusercontent.com/23135687/75138360-52389f80-56ea-11ea-80f4-1833ef97ef9f.png)

here is my command

`python3 fine_tune.py -bsz=8 -dr=0.2 -lr=0.001 -path=${root/trade-dst/save/TRADE-multiwozdst/HDD400BSZ32DR0.2ACC-0.4455} -exceptd=${taxi}
`

**Comment by jasonwu0731** [comment]
Hi

The error is came from the path format. You can change the path to "save/TRADE_......" and it should work.
