### ISSUE TITLE
License info

### ISSUE THREAD

**Issue by naveross** [jasonwu0731/trade-dst#24]
Hi,

I've found MIT license notice at [README](https://github.com/jasonwu0731/trade-dst/blob/master/README.md).
Can you let me get your copyright notice?

Thanks!

**Comment by jasonwu0731** [comment]
Hi there is no issue of that. I have updated the readme.

**Comment by naveross** [comment]
Hi,

I'm afraid that my comment was not clear enough.

There was no issue on MIT license notice at your README.
I just needed to know how to state your copyright when I use trade-dst in my project.

The commit ddb509f removed a license notice that was very useful for users who wants to use trade-dst because the notice let them know how to use trade-dst without copyright issue.

So I sent a PR : https://github.com/jasonwu0731/trade-dst/pull/25
Please review this.

Sorry for bothering you.
Thanks!
