### ISSUE TITLE
The test slot list in fine_tune.py seems to be wrong.

### ISSUE THREAD

**Issue by leowang7267** [jasonwu0731/trade-dst#29]
In line 73: acc_test = model.evaluate(test_single, 1e7, SLOTS_LIST[3]), why you use  SLOTS_LIST instead of SLOTS_LIST_single?

**Comment by jasonwu0731** [comment]
Hi,
SLOTS_LIST[3] is actually the test slot for a single domain if you check [here](https://github.com/jasonwu0731/trade-dst/blob/b77fcf110af4fb286965966ce39e0d4f20d1d3b9/utils/utils_multiWOZ_DST.py#L455). You can check the values of both list, they should be the same I guess.
