### ISSUE TITLE
Python3 Incompatability 

### ISSUE THREAD

**Issue by RylanC24** [jasonwu0731/trade-dst#3]
The README indicates a python3 interpreter should be used to run the repo but it is not actually python3 compatible.

**Comment by jasonwu0731** [comment]
Thanks for pointing this out. Which python version are you using? Can you list those incompatible dependencies?

**Comment by RylanC24** [comment]
I am using python 3.6. The `create_data.py` file will not work with any python3 interpreter. It has a number of python2 style `print` statements, a few instances of `file()`, `unicode` checks, and uses `urllib.urlopen()`, all of which are deprecated in python3. If you run the script with a python3 interpreter you should see all the errors.

**Comment by jasonwu0731** [comment]
Got it. Now I have migrated create_data.py to python3 compatible. 

Hope it help. :)

**Comment by RylanC24** [comment]
Thanks! I'll give it a shot and let you know if I run into any other issues
