### ISSUE TITLE
How to generate words beyond the vocabulary ?

### ISSUE THREAD

**Issue by gaoisbest** [jasonwu0731/trade-dst#31]
As the paper says in the end of Section 2.2 State Generator
```
Note that due to Eq (2), our model is able to generate words even if they are not pre-defined in the vocabulary.
```
but as the [code](https://github.com/jasonwu0731/trade-dst/blob/master/models/TRADE.py#L453) shows, `p_context_ptr = torch.zeros(p_vocab.size())`, does that mean it **restrict** the words must be in pre-defined vocabulary ? 

For example, the vocabulary size is 100, but we have a word id in `story` is 103.

Thanks a lot

**Comment by jasonwu0731** [comment]
Hi, please check issue #15 for an explanation.
