### ISSUE TITLE
When performing zero-shot DST, what's the embeddings of unseen domain & slots?

### ISSUE THREAD

**Issue by zqwerty** [jasonwu0731/trade-dst#32]
Are the embeddings of unseen slots randomly initialized?

**Comment by jasonwu0731** [comment]
Hi,

For the zero-shot experiment, in this implementation, a slot will still be a random vector if it does not appear in other domains.  

We did try to initialize them with Glove and Char embedding (basically you just need to modify [this part](https://github.com/jasonwu0731/trade-dst/blob/b77fcf110af4fb286965966ce39e0d4f20d1d3b9/models/TRADE.py#L360)), but I cannot recall the results now.

**Comment by zqwerty** [comment]
Thanks!
