### ISSUE TITLE
Problem of the train_dial.json

### ISSUE THREAD

**Issue by mianzhang** [jasonwu0731/trade-dst#33]
Hi,

Thanks for sharing the codes. In the train_dials.json, for each dialogue, the last utterance from the agent is directly dropped, why?
Looking for your reply.

Best,
Mian

**Comment by jasonwu0731** [comment]
Hi @mianzhang 

DST task is to predict system belief given the current conversation (u_1, s_1, ..., u_t), so we don't take system response at turn t (s_t) as input. We need state at turn t, the one we care in DST, to generate s_t.

**Comment by mianzhang** [comment]
I get it. Thanks a lot.
