### ISSUE TITLE
Implementation of model-agnostic meta-learning based on trade.

### ISSUE THREAD

**Issue by ha-lins** [jasonwu0731/trade-dst#34]
Hi everyone,

I implemented model-agnostic meta-learning (MAML) for dialogue state tracking (DST) based on trade in this [repo](https://github.com/ha-lins/MAML-DST). The implementation is similar to [MERET](https://www.aclweb.org/anthology/2020.acl-main.636.pdf). My implementation achieves good results in the few-shot setting.

![image](https://user-images.githubusercontent.com/22448743/115137502-1df41100-a059-11eb-9c4e-df0646172c20.png)

Feel free to look at it. : )

**Comment by jasonwu0731** [comment]
Good to hear that, @ha-lins !
