### ISSUE TITLE
Some questions about your data processing scripts

### ISSUE THREAD

**Issue by Auracion** [jasonwu0731/trade-dst#4]
Why didn't clean the values in **leave at** and **arrive by** as they did in https://github.com/budzianowski/multi-domain-belief-tracking ? And what does the condition **clean_value = True** use for in the function **normalize(text, clean_value=True)** in the file **create_data.py**? Has it been set to **True** during your experiment? Or it's just a useless part you forget to delete it.

**Comment by jasonwu0731** [comment]
Hi @Auracion,

1. You can add more cleaning process if you want.
2. About that part of the code, you can check this repo, I followed their preprocess somehow. 
https://github.com/budzianowski/multiwoz
